### ISSUE TITLE
Documentation merge with the global sepal doc 

### ISSUE THREAD

**Issue by 12rambau** [sig-gis/SEPAL-CEO#44]
The documentation have been merged with the sepal-doc and is available online. 

I describe the modifications in the following issue : https://github.com/openforis/sepal-doc/issues/4

I will add you as contributors of the doc when I’ll solve the bot problem on the repository.

If you see typos or problem you can use as many PR as you see fit

**Comment by kdyson** [comment]
Fantastic, thanks!
